### ISSUE TITLE
Smth wrong with initialization of LEDSetting.Regions

### ISSUE THREAD

**Issue by vsklamm** [elemc/msikeyboard#1]
Запуск примера с сайта
```
$ msikeyboard -left white:high -middle blue:high -right red:high -mode normal
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/elemc/msikeyboard/gomsikeyboard.init.0()
	/home/vsklamm/go/src/github.com/elemc/msikeyboard/gomsikeyboard/themes.go:18 +0x6d
```
I tried to initialize map before ```cool.Regions["left"] = green```, but it does nothing

**Comment by elemc** [comment]
Вроде пофиксил, проверь, пожалуйста.

**Comment by vsklamm** [comment]
```
root@SMAUG:~/go/bin# ./msikeyboard
2018/08/10 12:16:36 starting HTTP server...
2018/08/10 12:16:36 starting D-Bus server
^C
root@SMAUG:~/go/bin# ./msikeyboard -left white:high -middle blue:high -right red:high -mode normal
panic: assignment to entry in nil map

goroutine 1 [running]:
main.main()
	/home/vsklamm/go/src/github.com/elemc/msikeyboard/main.go:91 +0x744
```

**Comment by elemc** [comment]
Еще разик попробуй.
